version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - type: bind
        source: ./api
        target: /go/src
    ports:
      - target: 3000
        published: ${WEB_PORT:-3000}
        protocol: tcp
        mode: host
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-gin}
      - DB_USERNAME=${DB_USER:-gin}
      - DB_PASSWORD=${DB_PASS:-secret}
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME:-gin}
      - MYSQL_USER=${DB_USER:-gin}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

volumes:
  db-store:
